[project]
name = "binslt"
version = "0.1.0"
description = "Library for calculation of predissociation lifetimes of diatomic molecules"
authors = [
  { name="G M", email="georgi.mitev.16@ucl.ac.uk" }
]
readme = "README.md"
requires-python = ">=3.10"

# Dependencies your package needs
dependencies = [
  "pandas",
  "numpy",
  "matplotlib",
  "scipy",
  "quantiphy",
  "tqdm",
  "uncertainties",
  "pandarallel",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]